// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pbClient/pbClient.proto

package pbClient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ack           uint64                 `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	Type          uint32                 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_pbClient_pbClient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_pbClient_pbClient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_pbClient_pbClient_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetAck() uint64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *Envelope) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_pbClient_pbClient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_pbClient_pbClient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_pbClient_pbClient_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Logout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logout) Reset() {
	*x = Logout{}
	mi := &file_pbClient_pbClient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_pbClient_pbClient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_pbClient_pbClient_proto_rawDescGZIP(), []int{2}
}

func (x *Logout) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Talk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Talk) Reset() {
	*x = Talk{}
	mi := &file_pbClient_pbClient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Talk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Talk) ProtoMessage() {}

func (x *Talk) ProtoReflect() protoreflect.Message {
	mi := &file_pbClient_pbClient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Talk.ProtoReflect.Descriptor instead.
func (*Talk) Descriptor() ([]byte, []int) {
	return file_pbClient_pbClient_proto_rawDescGZIP(), []int{3}
}

func (x *Talk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Walk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heading       uint32                 `protobuf:"varint,1,opt,name=heading,proto3" json:"heading,omitempty"`
	X             uint32                 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             uint32                 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Walk) Reset() {
	*x = Walk{}
	mi := &file_pbClient_pbClient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Walk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Walk) ProtoMessage() {}

func (x *Walk) ProtoReflect() protoreflect.Message {
	mi := &file_pbClient_pbClient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Walk.ProtoReflect.Descriptor instead.
func (*Walk) Descriptor() ([]byte, []int) {
	return file_pbClient_pbClient_proto_rawDescGZIP(), []int{4}
}

func (x *Walk) GetHeading() uint32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *Walk) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Walk) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_pbClient_pbClient_proto protoreflect.FileDescriptor

const file_pbClient_pbClient_proto_rawDesc = "" +
	"\n" +
	"\x17pbClient/pbClient.proto\x12\bpbClient\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\x04R\x03ack\x12\x12\n" +
	"\x04type\x18\x03 \x01(\rR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"?\n" +
	"\x05Login\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\x06Logout\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\" \n" +
	"\x04Talk\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\x04Walk\x12\x18\n" +
	"\aheading\x18\x01 \x01(\rR\aheading\x12\f\n" +
	"\x01x\x18\x02 \x01(\rR\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\rR\x01yB\vZ\t/pbClientb\x06proto3"

var (
	file_pbClient_pbClient_proto_rawDescOnce sync.Once
	file_pbClient_pbClient_proto_rawDescData []byte
)

func file_pbClient_pbClient_proto_rawDescGZIP() []byte {
	file_pbClient_pbClient_proto_rawDescOnce.Do(func() {
		file_pbClient_pbClient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbClient_pbClient_proto_rawDesc), len(file_pbClient_pbClient_proto_rawDesc)))
	})
	return file_pbClient_pbClient_proto_rawDescData
}

var file_pbClient_pbClient_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pbClient_pbClient_proto_goTypes = []any{
	(*Envelope)(nil), // 0: pbClient.Envelope
	(*Login)(nil),    // 1: pbClient.Login
	(*Logout)(nil),   // 2: pbClient.Logout
	(*Talk)(nil),     // 3: pbClient.Talk
	(*Walk)(nil),     // 4: pbClient.Walk
}
var file_pbClient_pbClient_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pbClient_pbClient_proto_init() }
func file_pbClient_pbClient_proto_init() {
	if File_pbClient_pbClient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbClient_pbClient_proto_rawDesc), len(file_pbClient_pbClient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbClient_pbClient_proto_goTypes,
		DependencyIndexes: file_pbClient_pbClient_proto_depIdxs,
		MessageInfos:      file_pbClient_pbClient_proto_msgTypes,
	}.Build()
	File_pbClient_pbClient_proto = out.File
	file_pbClient_pbClient_proto_goTypes = nil
	file_pbClient_pbClient_proto_depIdxs = nil
}
